AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The lambda to write referral codes to RDS

Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: support
  Stage:
    Description: Set by RiffRaff on each deploy
    Type: String
    AllowedValues:
      - CODE
      - PROD
  DeployBucket:
    Description: Bucket to copy files to
    Type: String
    Default: membership-dist
  SecurityGroupToAccessPostgres:
    Description: Security group to access the RDS instance
    Type: String
  VpcSubnets:
    Description: Subnets for RDS access
    Type: List<AWS::EC2::Subnet::Id>
  StreamArn:
    Description: ARN of the kinesis stream
    Type: String

Mappings:
  StageMap:
    CODE:
      DomainName: contribution-referrals-code.support.guardianapis.com
      CorsOrigin: "'*'"
    PROD:
      DomainName: contribution-referrals.support.guardianapis.com
      CorsOrigin: "'*'"

Conditions:
  IsProd: !Equals [ !Ref Stage, "PROD" ]

Globals:
  Api:
    Cors:
      AllowOrigin: !FindInMap [ StageMap, !Ref Stage, CorsOrigin ]
      AllowHeaders: "'Content-Type'"
      AllowMethods: "'*'"

Resources:

  WriteReferralToRdsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub contributions-referrals-create-code-${Stage}
      Description: A lambda for saving referral codes to rds
      Runtime: nodejs10.x
      Handler: create-code/lambda/lambda.handler
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          Stage: !Ref Stage
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/contributions-referrals/contributions-referrals.zip
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupToAccessPostgres
        SubnetIds: !Ref VpcSubnets
      Policies:
        # there are some extra permissions needed for a lambda to access resources in a VPC
        # https://docs.aws.amazon.com/lambda/latest/dg/vpc.html
        # hence this role rather than BasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - ssm:GetParametersByPath
              - ssm:GetParameter
            Resource:
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/contributions-referrals/db-config/${Stage}
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/contributions-referrals/idapi/${Stage}/*
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/referral'
            Method: post

  BrazeUploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub contributions-referrals-braze-upload-${Stage}
      Description: The lambda to send referrals data to Braze
      Runtime: nodejs10.x
      Handler: braze-upload/lambda/lambda.handler
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          Stage: !Ref Stage
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/contributions-referrals/contributions-referrals.zip
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupToAccessPostgres
        SubnetIds: !Ref VpcSubnets
      Policies:
        # there are some extra permissions needed for a lambda to access resources in a VPC
        # https://docs.aws.amazon.com/lambda/latest/dg/vpc.html
        # hence this role rather than BasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - ssm:GetParametersByPath
            Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/contributions-referrals/db-config/${Stage}
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !Ref StreamArn
            BatchSize: 10
            StartingPosition: LATEST

  DomainName:
    Type: "AWS::ApiGateway::DomainName"
    Properties:
      RegionalCertificateArn: # only for *.support.guardianapis.com
        !Sub arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/b384a6a0-2f54-4874-b99b-96eeff96c009
      DomainName: !FindInMap [ StageMap, !Ref Stage, DomainName ]
      EndpointConfiguration:
        Types:
          - REGIONAL

  BasePathMapping:
    Type: "AWS::ApiGateway::BasePathMapping"
    Properties:
      RestApiId: !Ref ServerlessRestApi # auto generated by the Transform
      DomainName: !Ref DomainName
      Stage: !Sub Prod
    DependsOn: ServerlessRestApiProdStage # auto generated by the Transform

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: support.guardianapis.com.
      Name: !FindInMap [ StageMap, !Ref Stage, DomainName ]
      Comment: !Sub CNAME for contributions referrals endpoint ${Stage}
      Type: CNAME
      TTL: '120'
      ResourceRecords:
        - !GetAtt [ DomainName, RegionalDomainName ]

  WriteReferralToRdsAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:contributions-dev
      AlarmName: !Sub Referral write to rds failed in ${Stage}
      AlarmDescription: Users referral code is not being stored
      MetricName: ExecutionsFailed
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref WriteReferralToRdsLambda
      ComparisonOperator: GreaterThanThreshold
      Threshold: 1
      Period: 600
      EvaluationPeriods: 1
      Statistic: Sum
