AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The lambda to send referrals data to Braze

Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: support
  Stage:
    Description: Set by RiffRaff on each deploy
    Type: String
    AllowedValues:
      - CODE
      - PROD
  DeployBucket:
    Description: Bucket to copy files to
    Type: String
    Default: membership-dist
  SecurityGroupToAccessPostgres:
    Description: Security group to access the RDS instance
    Type: String
  VpcSubnets:
    Description: Subnets for RDS access
    Type: List<AWS::EC2::Subnet::Id>
  StreamArn:
    Description: ARN of the kinesis stream
    Type: String

Conditions:
  IsProd: !Equals [ !Ref Stage, "PROD" ]

Resources:
  BrazeUploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub contributions-referrals-braze-upload-${Stage}
      Description: The lambda to send referrals data to Braze
      Runtime: nodejs10.x
      Handler: braze-upload/lambda/lambda.handler
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          Stage: !Ref Stage
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/contributions-referrals-braze-upload/contributions-referrals-braze-upload.zip
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupToAccessPostgres
        SubnetIds: !Ref VpcSubnets
      Policies:
        # there are some extra permissions needed for a lambda to access resources in a VPC
        # https://docs.aws.amazon.com/lambda/latest/dg/vpc.html
        # hence this role rather than BasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - ssm:GetParametersByPath
            Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/contributions-referrals/braze-upload/db-config/${Stage}
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !Ref StreamArn
            BatchSize: 10
            StartingPosition: LATEST
